### ISSUE TITLE
Add a star command

### ISSUE THREAD

**Issue by Filnor** [SOBotics/CheckYerFlags#26]
Add a command to star messages. Syntax:

> @CheckYerFlags star <message id>

**Comment by Bhargav-Rao** [comment]
Why would this even be helpful? Using bots to star is a known method of abuse and can lead to either suspension or termination of the bot account, and does have repercussions on the bot owner.

**Comment by jdd-software** [comment]
Yeah I think a chat mod Madara have suspend bots for this... my advice is to not do it

**Comment by Filnor** [comment]
Ok, I have to row back here. It doesn't really help in anything. so consider the idea as discarded.
