### ISSUE TITLE
Allow dynamic goals

### ISSUE THREAD

**Issue by mvarendorff** [SOBotics/CheckYerFlags#44]
Flag ranks are nice and stuff but especially in the higher ranks the distance between ranks becomes rather long and less rewarding. It would be a nice option to be able to set oneself a goal which must not be named or have a specific context with something like `@Che goal 5000`.

**Comment by Filnor** [comment]
Some thoughts by me:
- The syntax for the command is fine, but I think that there should be 3 ways to use the `goal` command:
`@Che goal <flag count>` - Sets the goal to `<flag count>`. Reply with a message if the flag count is already reached.
`@Che goal` - Shows the set count of flags for the goal. Reply with a message if no goal is currently set.
`@Che goal del[ete]` - Deletes the set goal. Reply with a message if no goal is currently set.
- ~Minimal count: The goal should be higher than either 365 flags (which is currently the rank with the lowest flag count) or 500 flags (for which one gets a gold badge) in any case. Maybe also set a minimal difference from the users current flag count?~
- ~Don't add the goal if there's already a flag rank with that amount of flags.~ Only allow one Goal at a time.
- Automatically delete a goal if it's reached and the message was sent.

**Comment by Filnor** [comment]
Users requested a "distance" check when looking up their custom goal and the possibility to set a custom message when adding the goal
