### ISSUE TITLE
CheckYerFlag currently reboots when requesting the current flags

### ISSUE THREAD

**Issue by mvarendorff** [SOBotics/CheckYerFlags#47]
My assumption is that this comes from a UI change that SO made to the profile page.
`$(".g-col.g-row.fl-none").children()[6]` in the browser console returns an empty jQuery object.
I tried around a little and this absolutely sensible piece of code:
`$(".grid--cell.mt-auto.fc-black-350.fs-caption.lh-sm .grid.gs4.fd-column").children()[1].children[0].children[1].innerText` works fine at least in the console but I don't know how much of that is portable to the Python jQuery library (especially since the last two children "calls" are plain HTML attributes and not jQuery) and if there might not be a more intelligent way of doing the chaos I produced there but maybe there is something in that which you can use.

**Comment by Filnor** [comment]
Yeah, you've gotten this right with the UI change. I'll try to debug it with your solution. For the portability: You can wrap those children in jQuery again like this:
```js
//Mixed
$(selector).children()[1].children[0]
//Pure jQuery
$($(selector).children()[1]).children()[0]
```

I already use that in the current solution (somewhat).

Thanks for the selector code by the way, that surely saved me some time and allows me to publish the fix more quickly.
